version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis-dev:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - freecodecamp
networks:
  freecodecamp:
volumes:
  pgdata:
  redisdata:
